# Generated by Django 5.2.4 on 2025-08-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserInfo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadhistory",
            old_name="confidence",
            new_name="accuracy",
        ),
    ]
